from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
CATALOGS_DIR = DATA_DIR / "catalogs"

OUTPUT_DIR = BASE_DIR / "outputs"
REPORTS_DIR = OUTPUT_DIR / "reports"
CHARTS_DIR = OUTPUT_DIR / "charts"
ALERTS_DIR = OUTPUT_DIR / "alerts"

SOURCE_FILE = RAW_DIR / "Reportes de Apoyo SAF - Delitos Ingresados.xlsx"

ADDRESS_ALIAS_CATALOG_FILE = (
    CATALOGS_DIR / "address_aliases.csv"
)

NORMALIZED_DATA_FILE = (
    PROCESSED_DIR / "delitos_normalizados.csv"
)

ADDRESS_QUALITY_REPORT_FILE = (
    REPORTS_DIR / "reporte_normalizacion_direcciones.csv"
)

EXPECTED_COLUMNS = [
    "PARTE",
    "FECHA PARTE",
    "COD DESTACAMENTO",
    "UNIDAD POLICIAL PARTE",
    "RUC",
    "CRR IDCASO",
    "FECHA RECEPCION",
    "AÑO RECEPCION",
    "MES RECEPCION",
    "FECHA DENUNCIA",
    "NOMBRE CASO",
    "FISCALIA REGIONAL",
    "COD REGIONCASO",
    "FISCALIA",
    "COD FISCALIA",
    "FISCAL ASIGNADO",
    "RUT FISCAL ASIGNADO",
    "ORIGEN CASO",
    "FORMA INICIO",
    "ESTADO CASO",
    "FECHA TERMINO CASO",
    "AÑO TERMINO CASO",
    "CRR IDDELITO",
    "DELITO",
    "COD DELITO",
    "FAMILIA DELITO",
    "COD FAMILIADELITO",
    "FOCALIZADO",
    "FECHA DELITO",
    "HORA DELITO",
    "CLASIFICACION HORARIA DELITO",
    "LUGAR OCURRENCIA",
    "SITIO SUCESO",
    "MEDIO COMISION DELITO",
    "TIPO ARMA",
    "REGION DELITO",
    "COMUNA DELITO",
    "CALLE DIRECCION DELITO",
    "NUMERO DIRECCION DELITO",
    "DEPTO DIRECCION DELITO",
    "BLOCK DIRECCION DELITO",
    "CONJUNTO HABITACIONAL DIRECCION DELITO",
    "POBLACION DIRECCION DELITO",
    "TIPO IMPUTADO DELITO",
    "TIPO VICTIMA DELITO",
    "ACTUALIZACIÓN",
]

NULL_REPORT_FILE = (
    REPORTS_DIR / "reporte_valores_nulos.csv"
)

DUPLICATE_DETAIL_REPORT_FILE = (
    REPORTS_DIR / "reporte_duplicados_detalle.csv"
)

DUPLICATE_SUMMARY_REPORT_FILE = (
    REPORTS_DIR / "reporte_duplicados_resumen.csv"
)
